language: python

services:
  - docker

jobs:
  include:
  - name: "PowerDNS v4.2.0"
    env: POWERDNS_VERSION="v4.2.0"
  - name: "PowerDNS 4.1.10"
    env: POWERDNS_VERSION="4.1.10"

python:
  - "2.7"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"

install:
  - pip install python-coveralls
  - pip install .

# run tests
script:
  - pytest
  - pip install .
  - docker-compose up -d
  - sleep 5
  - ./test/run_certonly.sh test/pdns-credentials.ini

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
      tags: true
      python: "3.6"

after_success:
  - coveralls
