language: python

services:
  - docker

jobs:
  include:
  - name: "PowerDNS 4.1.10, python 2.7"
    python: "2.7"
    env:
      - POWERDNS_VERSION="4.1.10"
  - name: "PowerDNS 4.1.10, python 3.5"
    python: "3.5"
    env:
      - POWERDNS_VERSION="4.1.10"
  - name: "PowerDNS 4.1.10, python 3.7"
    python: "3.7"
    env:
      - POWERDNS_VERSION="4.1.10"
  # v4.2.0 is the default
  # - name: "PowerDNS v4.2.0"
  #   env: POWERDNS_VERSION="v4.2.0"


python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  # PyPy versions
  - "pypy3.5"

install:
  - pip install python-coveralls
  - pip install .

# run tests
script:
  - pytest
  - pip install .
  - COMPOSE_PROJECT_NAME="certbotpdns_$TRAVIS_JOB_ID" docker-compose run setup
  - sleep 5
  - chmod 0500 test/pdns-credentials.ini
  - ./test/run_certonly.sh test/pdns-credentials.ini

after_script:
  - COMPOSE_PROJECT_NAME="certbotpdns_$TRAVIS_JOB_ID" docker-compose down

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
      tags: true
      python: "3.6"

after_success:
  - coveralls
