language: python

services:
  - docker

env:
- POWERDNS_VERSION="4.1.10"
- POWERDNS_VERSION="v4.2.0"

# uses default POWERDNS_VERSION in docker-compose.yml
python:
  # PyPy versions
  - "3.5"
  - "3.7"
  - "pypy3.5"

install:
  - pip install python-coveralls
  - pip install .

# run tests
script:
  - pytest
  - pip install .
  - COMPOSE_PROJECT_NAME="certbotpdns_$TRAVIS_JOB_ID" docker-compose run setup
  - sleep 5
  - chmod 0500 test/pdns-credentials.ini
  - ./test/run_certonly.sh test/pdns-credentials.ini

after_script:
  - COMPOSE_PROJECT_NAME="certbotpdns_$TRAVIS_JOB_ID" docker-compose down

jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
      if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+ # match semver

after_success:
  - coveralls
