language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"

install:
  - pip install python-coveralls
  - pip install .

# run tests
script:
  - pytest

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
      tags: true
      python: "3.6"

after_success:
  - coveralls